
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'programID IMMEDIATE SEMICOLON COLON COMMA DAT MOV ADD SUB JMP JMZ CMP NOPprogram : directives\n    directives : directive directives\n                  | directivedirective : MOV IMMEDIATE COMMA IMMEDIATEdirective : ADD IMMEDIATE COMMA IMMEDIATEdirective : NOPdirective : SUB IMMEDIATE COMMA IMMEDIATEdirective : JMP IMMEDIATEdirective : JMZ IMMEDIATE COMMA IMMEDIATEdirective : CMP IMMEDIATE COMMA IMMEDIATE'
    
_lr_action_items = {'MOV':([0,3,6,15,23,24,25,26,27,],[4,4,-6,-8,-4,-5,-7,-9,-10,]),'ADD':([0,3,6,15,23,24,25,26,27,],[5,5,-6,-8,-4,-5,-7,-9,-10,]),'NOP':([0,3,6,15,23,24,25,26,27,],[6,6,-6,-8,-4,-5,-7,-9,-10,]),'SUB':([0,3,6,15,23,24,25,26,27,],[7,7,-6,-8,-4,-5,-7,-9,-10,]),'JMP':([0,3,6,15,23,24,25,26,27,],[8,8,-6,-8,-4,-5,-7,-9,-10,]),'JMZ':([0,3,6,15,23,24,25,26,27,],[9,9,-6,-8,-4,-5,-7,-9,-10,]),'CMP':([0,3,6,15,23,24,25,26,27,],[10,10,-6,-8,-4,-5,-7,-9,-10,]),'$end':([1,2,3,6,11,15,23,24,25,26,27,],[0,-1,-3,-6,-2,-8,-4,-5,-7,-9,-10,]),'IMMEDIATE':([4,5,7,8,9,10,18,19,20,21,22,],[12,13,14,15,16,17,23,24,25,26,27,]),'COMMA':([12,13,14,16,17,],[18,19,20,21,22,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'directives':([0,3,],[2,11,]),'directive':([0,3,],[3,3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> directives','program',1,'p_program','redcodeparse.py',11),
  ('directives -> directive directives','directives',2,'p_directives','redcodeparse.py',17),
  ('directives -> directive','directives',1,'p_directives','redcodeparse.py',18),
  ('directive -> MOV IMMEDIATE COMMA IMMEDIATE','directive',4,'p_directive_mov','redcodeparse.py',25),
  ('directive -> ADD IMMEDIATE COMMA IMMEDIATE','directive',4,'p_directive_add','redcodeparse.py',30),
  ('directive -> NOP','directive',1,'p_directive_nop','redcodeparse.py',35),
  ('directive -> SUB IMMEDIATE COMMA IMMEDIATE','directive',4,'p_directive_sub','redcodeparse.py',40),
  ('directive -> JMP IMMEDIATE','directive',2,'p_directive_jmp','redcodeparse.py',45),
  ('directive -> JMZ IMMEDIATE COMMA IMMEDIATE','directive',4,'p_directive_jmz','redcodeparse.py',50),
  ('directive -> CMP IMMEDIATE COMMA IMMEDIATE','directive',4,'p_directive_cmp','redcodeparse.py',55),
]
